# Generated by Django 5.0.1 on 2024-02-14 02:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LibroVenc', '0001_initial'),
        ('Medicamento', '0002_alter_medicamento_existencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('fechaVenta', models.DateField(default=django.utils.timezone.now)),
                ('importe', models.FloatField(default=0)),
                ('loteV', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='LibroVenc.librovenc')),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Medicamento.medicamento')),
            ],
        ),
    ]
