# Generated by Django 5.0.1 on 2024-02-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibroVenc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librovenc',
            name='cantidadRestante',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
