# Generated by Django 5.0.1 on 2024-02-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedicamento', models.CharField(max_length=30, unique=True)),
                ('grupo', models.CharField(blank=True, default='', max_length=30)),
                ('existencia', models.IntegerField(blank=True, default=0)),
                ('precio', models.FloatField(blank=True, default=0)),
                ('estado', models.CharField(blank=True, choices=[('dis', 'Disponible'), ('ago', 'Agotado'), ('def', 'Déficit'), ('con', 'Congelado')], default='dis', max_length=15)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
    ]
